dnf:
  - zsh
  - neovim
  - neofetch
  - inxi
  #- tio
  - wget
  - curl
  - rclone
  - ranger
  - mc
  - restic
  - p7zip
  - p7zip-plugins
  #- cryptsetup
  - ncdu
  #- tmux
  - btop
  - par2cmdline
  - bat
  - nmap-ncat
  - pandoc
  - ripgrep
  - tig
  - w3m
  - exa
  - speedtest-cli
  - dbus-x11
  - direnv
  - just
  - ncurses
  - wl-clipboard
  - gcc
  - make
rpm:
  - chezmoi: https://github.com/twpayne/chezmoi/releases/download/v2.40.3/chezmoi-2.40.3-x86_64.rpm
tar:
  - zellij: https://github.com/zellij-org/zellij/releases/download/v0.38.2/zellij-x86_64-unknown-linux-musl.tar.gz
binary:
  - nb: https://raw.github.com/xwmx/nb/master/nb
  - host-spawn: https://github.com/1player/host-spawn/releases/download/1.5.0/host-spawn-x86_64

