dnf:
  - zsh
  - neovim
  - neofetch
  - inxi
  - wget
  - curl
  - rclone
  - ranger
  - mc
  - restic
  - p7zip
  - p7zip-plugins
  - ncdu
  - btop
  - par2cmdline
  - bat
  - nmap-ncat
  - pandoc
  - ripgrep
  - tig
  - w3m
  - lsd
  - speedtest-cli
  - dbus-x11
  - direnv
  - ncurses
  - wl-clipboard
  - gcc
  - make
  - nodejs-npm
  - dconf
  - fzf
  - virt-viewer
rpm:
  - chezmoi: https://github.com/twpayne/chezmoi/releases/download/v2.51.0/chezmoi-2.51.0-x86_64.rpm
  - glow: https://github.com/charmbracelet/glow/releases/download/v1.5.1/glow-1.5.1.x86_64.rpm
  - cosign: https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-2.2.4-1.x86_64.rpm
tar:
  - zellij: https://github.com/zellij-org/zellij/releases/download/v0.40.1/zellij-x86_64-unknown-linux-musl.tar.gz
binary:
  - nb: https://raw.github.com/xwmx/nb/master/nb
  - host-spawn: https://github.com/1player/host-spawn/releases/download/v1.6.0/host-spawn-x86_64

